/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 23-oct.-2017 9:19:25 p. m. 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS "Categoria " CASCADE
;

DROP TABLE IF EXISTS Database CASCADE
;

DROP TABLE IF EXISTS Esrb CASCADE
;

DROP TABLE IF EXISTS Juego CASCADE
;

DROP TABLE IF EXISTS Juego_Categoria CASCADE
;

DROP TABLE IF EXISTS Jugador CASCADE
;

DROP TABLE IF EXISTS Puntaje CASCADE
;

/* Create Tables */

CREATE TABLE "Categoria "
(
	id_categoria integer NOT NULL,
	Nombre varchar(50) NULL,
	Descripcion varchar(150) NULL
)
;

CREATE TABLE Database
(
	id_database integer NOT NULL,
	Pais varchar(50) NULL,
	Nombre varchar(50) NULL,
	Descripcion varchar(150) NULL
)
;

CREATE TABLE Esrb
(
	id_esrb integer NOT NULL,
	Nombre varchar(50) NULL,
	Descripcion varchar(50) NULL
)
;

CREATE TABLE Juego
(
	id_Juego integer NOT NULL,
	Nombre varchar(50) NOT NULL,
	Esrb varchar(50) NULL,
	Descripcion varchar(150) NULL,
	Portada varchar(50) NULL,
	Numero_Jugadores integer NULL
)
;

CREATE TABLE Juego_Categoria
(
	id integer NOT NULL,
	Juego varchar(50) NULL,
	Categoria varchar(50) NULL
)
;

CREATE TABLE Jugador
(
    id_Jugador BIGSERIAL PRIMARY KEY,
	gamertag varchar(50) ,
	password varchar(50) ,
	nombre varchar(50) ,
	apellido varchar(50) ,
	email varchar(50) ,
	fecha_nacimiento timestamp without time zone ,
	pais varchar(50) ,
	avatar varchar(50) 
)
;

CREATE TABLE Puntaje
(
	id_puntaje integer NULL,
	Juego varchar(50) NULL,
	Jugador varchar(50) NULL,
	Fecha varchar(50) NULL,
	Puntaje varchar(50) NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE "Categoria " ADD CONSTRAINT PK_Categoria
	PRIMARY KEY (id_categoria)
;

ALTER TABLE Database ADD CONSTRAINT PK_Database
	PRIMARY KEY (id_database)
;

ALTER TABLE Esrb ADD CONSTRAINT PK_Esrb
	PRIMARY KEY (id_esrb)
;

ALTER TABLE Juego ADD CONSTRAINT PK_Juego
	PRIMARY KEY (id_Juego)
;

ALTER TABLE Juego_Categoria ADD CONSTRAINT PK_Juego_Categoria
	PRIMARY KEY (id)
;


/* Create Table Comments, Sequences for Autonumber Columns */

COMMENT ON TABLE Database
	IS 'om'
;
